---
title: "AHR_28th"
output: html_document
date: "2024-09-11"
---

```{r}
system('g++ --version')

```

```{r}

options(repos = c(CRAN = "https://cloud.r-project.org"))

install.packages("ggplot2")
install.packages("dplyr")
install.packages("reactable")
install.packages("readxl")

library(ggplot2)
library(dplyr)
library(readxl)
library(reactable)

```

```{r}
library(readxl)

# Loading the sheets from the Excel workbook
ahr_data <- read_excel("C:/Shefali/Reason Foundation/Highway report_28th/ahr_data_28th.xlsx", sheet = "AHR Data")
scores_rankings <- read_excel("C:/Shefali/Reason Foundation/Highway report_28th/ahr_data_28th.xlsx", sheet = "Scores & Rankings")
disbursement_data <- read_excel("C:/Shefali/Reason Foundation/Highway report_28th/ahr_data_28th.xlsx", sheet = "Disbursement Data")

```


```{r}
# Capital Disbursement vs. Maintenance Disbursement
#It showS how much each state spends on infrastructure maintenance relative to its capital investment.
library(ggplot2)
ggplot(ahr_data, aes(x = capital_disbursement, y = maintenance_disbursement)) +
  geom_point(color = "blue") +
  labs(title = "Capital Disbursement vs. Maintenance Disbursement by State",
       x = "Capital Disbursement", y = "Maintenance Disbursement") +
  theme_minimal()

```


```{r}
# Chart 2: Urban Lane Miles Percentage vs. Urban Interstate Poor Condition
# It highlights whether a higher proportion of urban lane miles correlates with poor road conditions

ggplot(ahr_data, aes(x = pct_urban_lane_miles, y = urban_interstate_poor_percent)) +
  geom_point(color = "red") +
  labs(title = "Urban Lane Miles Percentage vs. Urban Interstate Poor Condition",
       x = "Urban Lane Miles Percentage", y = "Urban Interstate Poor Condition Percentage") +
  theme_minimal()

```


```{r}
# Chart 3: State Average Congestion Hours
#comparison of traffic congestion between states, highlighting those with the most and least congestion.

ggplot(ahr_data, aes(x = reorder(state, state_avg_congestion_hours), y = state_avg_congestion_hours)) +
  geom_bar(stat = "identity", fill = "green") +
  coord_flip() +
  labs(title = "State Average Congestion Hours", x = "State", y = "Average Congestion Hours") +
  theme_minimal()


```



```{r}
# Chart 4: Comparison of Fatalities per 100M VMT (Rural, Urban, Other)
#Identifies which regions are experiencing the highest vehicle fatality rates.

ggplot(ahr_data, aes(x = state)) +
  geom_bar(aes(y = rural_fatalities_per_100m_VMT), stat = "identity", fill = "blue", alpha = 0.6) +
  geom_bar(aes(y = urban_fatalities_per_100m_VMT), stat = "identity", fill = "red", alpha = 0.6) +
  geom_bar(aes(y = other_fatalities_per_100m_VMT), stat = "identity", fill = "purple", alpha = 0.6) +
  labs(title = "Fatalities per 100M VMT by Area Type", x = "State", y = "Fatalities per 100M VMT") +
  theme_minimal()


```


```{r}
# Scatter plot: Actual Value vs. Expected Value by Key Metrics
ggplot(disbursement_data, aes(x = exp_value, y = value, color = key_metrics)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") + # Line showing where value = exp_value
  labs(title = "Actual vs. Expected Disbursement by Key Metrics",
       x = "Expected Disbursement Value", y = "Actual Disbursement Value") +
  theme_minimal()

```

```{r}
# Bar chart: Disbursement Value by State and Key Metric
ggplot(disbursement_data, aes(x = state, y = value, fill = key_metrics)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Disbursement Value by State and Key Metric",
       x = "State", y = "Disbursement Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```

```{r}
# Bar chart: State Rankings by Overall Score
ggplot(scores_rankings, aes(x = reorder(state, overall_score), y = overall_score)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "State Rankings by Overall Score", x = "State", y = "Overall Score") +
  theme_minimal()


```

```{r}
#Poor Road Conditions vs. Scores - 
# Scatter plot: Poor Road Conditions vs. Urban Interstate Poor Percent Score
ggplot(scores_rankings, aes(x = urban_interstate_poor_percent_score, y = poor_bridges_percent_score)) +
  geom_point() +
  geom_smooth(method = "lm", col = "blue") +
  labs(title = "Urban Interstate Poor Percent Score vs. Poor Bridges Percent Score",
       x = "Urban Interstate Poor Percent Score", y = "Poor Bridges Percent Score") +
  theme_minimal()

```


```{r}
# Bar chart: Disbursement Values by Key Metrics
ggplot(disbursement_data, aes(x = state, y = value, fill = key_metrics)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Disbursement by Key Metrics Across States",
       x = "State", y = "Disbursement Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```


```{r}
# Scatter plot: Expected vs. Actual Disbursement by State
ggplot(disbursement_data, aes(x = exp_value, y = value, color = state)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") + # Line for equal values
  labs(title = "Expected vs. Actual Disbursement by State",
       x = "Expected Disbursement", y = "Actual Disbursement") +
  theme_minimal()


```


```{r}
library(dplyr)
library(reactable)

score_table <- scores_rankings %>%
  select(state, overall_score, rural_interstate_poor_percent_score, urban_interstate_poor_percent_score, 
         rural_fatalities_per_100m_VMT_score, urban_fatalities_per_100m_VMT_score, poor_bridges_percent_score, 
         state_avg_congestion_hours_score, overall_score_rank, rural_interstate_poor_percent_score_rank, 
         urban_interstate_poor_percent_score_rank, rural_fatalities_per_100m_VMT_score_rank, 
         urban_fatalities_per_100m_VMT_score_rank, poor_bridges_percent_score_rank, state_avg_congestion_hours_score_rank) %>%
  arrange(desc(overall_score))

# Normalization: calculating min and max for scaling
min_score <- min(score_table$overall_score, na.rm = TRUE)
max_score <- max(score_table$overall_score, na.rm = TRUE)

# assigning colors based on normalized scores
color_scale_revised <- function(value) {
  if (is.na(value)) return("transparent")
  normalized <- (value - min_score) / (max_score - min_score)
  rgb <- colorRamp(c("#66bb6a", "#ffeb3b", "#ef5350"))(normalized)
  rgb <- paste("rgb(", paste(rgb, collapse = ","), ")", sep = "")
  return(rgb)
}

# Creating the Reactable Table
reactable(
  data = score_table,
  filterable = TRUE,
  defaultSorted = list(overall_score = "desc"),
  columns = list(
    state = colDef(name = "State"),
    
    overall_score = colDef(
      name = "Overall Score",
      format = colFormat(digits = 2),
      style = function(value) {
        list(background = color_scale_revised(value))
      }
    ),
    
    rural_interstate_poor_percent_score = colDef(
      name = "Rural Interstate Poor Score",
      format = colFormat(digits = 2),
      style = function(value) {
        list(background = color_scale_revised(value))
      }
    ),
    
    urban_interstate_poor_percent_score = colDef(
      name = "Urban Interstate Poor Score",
      format = colFormat(digits = 2),
      style = function(value) {
        list(background = color_scale_revised(value))
      }
    ),
    
    rural_fatalities_per_100m_VMT_score = colDef(
      name = "Rural Fatalities Score",
      format = colFormat(digits = 2),
      style = function(value) {
        list(background = color_scale_revised(value))
      }
    ),
    
    urban_fatalities_per_100m_VMT_score = colDef(
      name = "Urban Fatalities Score",
      format = colFormat(digits = 2),
      style = function(value) {
        list(background = color_scale_revised(value))
      }
    ),
    
    poor_bridges_percent_score = colDef(
      name = "Poor Bridges Score",
      format = colFormat(digits = 2),
      style = function(value) {
        list(background = color_scale_revised(value))
      }
    ),
    
    state_avg_congestion_hours_score = colDef(
      name = "Congestion Hours Score",
      format = colFormat(digits = 2),
      style = function(value) {
        list(background = color_scale_revised(value))
      }
    ),
    
    overall_score_rank = colDef(
      name = "Overall Rank",
      format = colFormat(digits = 0)
    ),
    
    rural_interstate_poor_percent_score_rank = colDef(
      name = "Rural Interstate Poor Rank",
      format = colFormat(digits = 0)
    ),
    
    urban_interstate_poor_percent_score_rank = colDef(
      name = "Urban Interstate Poor Rank",
      format = colFormat(digits = 0)
    ),
    
    rural_fatalities_per_100m_VMT_score_rank = colDef(
      name = "Rural Fatalities Rank",
      format = colFormat(digits = 0)
    ),
    
    urban_fatalities_per_100m_VMT_score_rank = colDef(
      name = "Urban Fatalities Rank",
      format = colFormat(digits = 0)
    ),
    
    poor_bridges_percent_score_rank = colDef(
      name = "Poor Bridges Rank",
      format = colFormat(digits = 0)
    ),
    
    state_avg_congestion_hours_score_rank = colDef(
      name = "Congestion Hours Rank",
      format = colFormat(digits = 0)
    )
  )
)

```


```{r}
head(ahr_data)
head(scores_rankings)
head(disbursement_data)

```



```{r}

library(readxl)
library(dplyr)
library(reactable)
library(htmltools)


create_bar <- function(value, max_value, color) {
  
  width <- paste0((value / max_value) * 100, "%")
  
  
  div(style = "display: flex; align-items: center; white-space: nowrap;",  
      div(style = paste("width:", width, "; background-color:", color, "; height: 15px; margin-right: 5px;", sep = "")),  
      div(sprintf("%.2f", value))  
  )
}

# Calculating the max values 
max_overall_score <- max(score_table$overall_score, na.rm = TRUE)
max_rural_interstate_poor_percent <- max(score_table$rural_interstate_poor_percent_score, na.rm = TRUE)
max_urban_interstate_poor_percent <- max(score_table$urban_interstate_poor_percent_score, na.rm = TRUE)
max_rural_fatalities <- max(score_table$rural_fatalities_per_100m_VMT_score, na.rm = TRUE)
max_urban_fatalities <- max(score_table$urban_fatalities_per_100m_VMT_score, na.rm = TRUE)
max_poor_bridges <- max(score_table$poor_bridges_percent_score, na.rm = TRUE)
max_congestion_hours <- max(score_table$state_avg_congestion_hours_score, na.rm = TRUE)

reactable(
  data = score_table,
  filterable = TRUE,
  defaultSorted = list(overall_score = "desc"),
  columns = list(
    state = colDef(name = "State", minWidth = 120),  
    
    overall_score = colDef(
      name = "Overall Score",
      cell = function(value) {
        create_bar(value, max_overall_score, "#FFCC33")  # Yellow bar for overall score
      },
      minWidth = 150  
    ),
    
    rural_interstate_poor_percent_score = colDef(
      name = "Rural Interstate Poor Score",
      cell = function(value) {
        create_bar(value, max_rural_interstate_poor_percent, "#66bb6a")  # Green bar for rural interstate poor score
      },
      minWidth = 150  
    ),
    
    urban_interstate_poor_percent_score = colDef(
      name = "Urban Interstate Poor Score",
      cell = function(value) {
        create_bar(value, max_urban_interstate_poor_percent, "#FF6633")  # Red bar for urban interstate poor score
      },
      minWidth = 150  
    ),
    
    rural_fatalities_per_100m_VMT_score = colDef(
      name = "Rural Fatalities Score",
      cell = function(value) {
        create_bar(value, max_rural_fatalities, "#990000")  # Dark red for rural fatalities score
      },
      minWidth = 150  
    ),
    
    urban_fatalities_per_100m_VMT_score = colDef(
      name = "Urban Fatalities Score",
      cell = function(value) {
        create_bar(value, max_urban_fatalities, "#3399cc")  # Blue for urban fatalities score
      },
      minWidth = 150  
    ),
    
    poor_bridges_percent_score = colDef(
      name = "Poor Bridges Score",
      cell = function(value) {
        create_bar(value, max_poor_bridges, "#999999")  # Grey for poor bridges score
      },
      minWidth = 150  
    ),
    
    state_avg_congestion_hours_score = colDef(
      name = "Congestion Hours Score",
      cell = function(value) {
        create_bar(value, max_congestion_hours, "#FFCC33")
      },
      minWidth = 150  
    ),
    
    overall_score_rank = colDef(
      name = "Overall Rank",
      format = colFormat(digits = 0),
      minWidth = 100
    ),
    
    rural_interstate_poor_percent_score_rank = colDef(
      name = "Rural Interstate Poor Rank",
      format = colFormat(digits = 0),
      minWidth = 100
    ),
    
    urban_interstate_poor_percent_score_rank = colDef(
      name = "Urban Interstate Poor Rank",
      format = colFormat(digits = 0),
      minWidth = 100
    ),
    
    rural_fatalities_per_100m_VMT_score_rank = colDef(
      name = "Rural Fatalities Rank",
      format = colFormat(digits = 0),
      minWidth = 100
    ),
    
    urban_fatalities_per_100m_VMT_score_rank = colDef(
      name = "Urban Fatalities Rank",
      format = colFormat(digits = 0),
      minWidth = 100
    ),
    
    poor_bridges_percent_score_rank = colDef(
      name = "Poor Bridges Rank",
      format = colFormat(digits = 0),
      minWidth = 100
    ),
    
    state_avg_congestion_hours_score_rank = colDef(
      name = "Congestion Hours Rank",
      format = colFormat(digits = 0),
      minWidth = 100
    )
  ),
  defaultPageSize = 10,
  striped = TRUE,
  highlight = TRUE,
  bordered = TRUE,
  searchable = TRUE,
  showPageSizeOptions = TRUE,
  paginationType = "jump"
)


```
```{r}

# Creating table with overall rank and state
score_table <- scores_rankings %>%
  select(state, overall_score_rank) %>%
  arrange(overall_score_rank)


reactable(
  data = score_table,
  filterable = FALSE, 
  columns = list(
    overall_score_rank = colDef(name = "Overall", format = colFormat(digits = 0), minWidth = 80),  # Rank column
    state = colDef(name = "State", minWidth = 150)  
  ),
  defaultPageSize = 10, 
  striped = TRUE,  
  bordered = TRUE,  
  paginationType = "simple",  
  defaultSorted = list(overall_score_rank = "asc")  
)

```


```{r}

library(dplyr)
library(reactable)  
library(htmltools)  


score_table_alphabetical <- scores_rankings %>%
  select(state, overall_score_rank) %>%
  arrange(state)  # Sort alphabetically


max_score_rank <- max(score_table_alphabetical$overall_score_rank, na.rm = TRUE)


create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  bar_style <- list(
    display = "inline-block",
    width = paste0(100 * value / max_value, "%"),  
    height = "15px",
    backgroundColor = color
  )
  htmltools::div(style = bar_style, format(value, big.mark = ",", scientific = FALSE)) 
}

# reactable table
reactable(
  data = score_table_alphabetical,
  filterable = FALSE, 
  columns = list(
    state = colDef(name = "State", minWidth = 150),  
    overall_score_rank = colDef(
      name = "Overall Rank", 
      cell = function(value) {
        create_bar_chart(value, max_score_rank, "#66bb6a")  
      },
      minWidth = 180  
    )
  ),
  defaultPageSize = 10,  
  striped = TRUE,  
  highlight = TRUE, 
  bordered = TRUE,  
  paginationType = "simple",  
  defaultSorted = list(state = "asc")  # Sorting alphabetically by state
)


```


```{r}
library(dplyr)
library(usmap)
library(readxl)  
library(ggplot2)
```


```{r}
# Check the structure of the us_map data
map_data <- usmap::us_map(regions = "states")
str(map_data)

```



```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(maps) 


score_table <- scores_rankings %>%
  select(state, overall_score_rank) %>%
  mutate(state = tolower(state))  


states_map <- map_data("state")


map_data <- left_join(states_map, score_table, by = c("region" = "state"))


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state"))

# Plot the U.S. map
ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = overall_score_rank), color = "white") +
  scale_fill_gradientn(colors = c("green", "yellow", "orange", "red"),
                       na.value = "gray",  # Color for missing data
                       breaks = c(1, 10, 20, 30, 40, 50),
                       labels = c("1", "10", "20", "30", "40", "50")) +
  theme_minimal() +
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = overall_score_rank), size = 3, color = "black") +
  labs(title = "Overall Highway Performance Rank", fill = "Rank")


```


```{r}
library(readxl)
library(dplyr)
library(reactable)  
library(htmltools) 

lane_miles_table <- ahr_data %>%
  filter(state != "United States") %>%
  select(state, state_tot_lane_miles) %>%
  arrange(desc(state_tot_lane_miles)) %>%
  mutate(Rank = row_number()) %>%
  select(Rank, state, state_tot_lane_miles)

us_total <- data.frame(
  Rank = NA,  
  state = "U.S. Total",
  state_tot_lane_miles = sum(lane_miles_table$state_tot_lane_miles, na.rm = TRUE)
)

lane_miles_table <- bind_rows(lane_miles_table, us_total)

max_lane_miles <- max(lane_miles_table$state_tot_lane_miles, na.rm = TRUE)

create_bar_chart <- function(value, max_value, color = "#66bb6a") {
  if (is.na(value)) return("")  
  width_percent <- 100 * value / max_value  
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"),  
    height = "15px",
    backgroundColor = color,
    whiteSpace = "nowrap",  
    textAlign = "center",   
    verticalAlign = "middle" 
  )
  div_container <- div(style = bar_style, format(round(value), big.mark = ",", scientific = FALSE))
  return(div_container)
}

htmltools::tagList(
  htmltools::tags$h3("STATE-CONTROLLED HIGHWAY MILEAGE"),
  
  reactable(
    lane_miles_table,
    columns = list(
      Rank = colDef(name = "Size", minWidth = 50, align = "center", cell = function(value) {
        if (is.na(value)) {
          ""  
        } else {
          value
        }
      }),
      state = colDef(name = "State", minWidth = 120, align = "center"),
      state_tot_lane_miles = colDef(
        name = "Lane-Miles",
        cell = function(value, index) {
          if (lane_miles_table$state[index] == "U.S. Total") {
            format(round(value), big.mark = ",", scientific = FALSE)  
          } else {
            create_bar_chart(value, max_lane_miles, "#FFCC33")  
          }
        },
        minWidth = 300,  
        align = "center"  
      )
    ),
    defaultSorted = list(Rank = "asc"),
    bordered = TRUE,
    highlight = TRUE,
    compact = TRUE,  
    paginationType = "simple"
  )
)



```


```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(maps)  


score_table <- scores_rankings %>%
  select(state, capital_disbursement_perlm_score_rank) %>%
  mutate(
    state_lower = tolower(state), 
    state_abb = state.abb[match(state, state.name)] 
  )

states_map <- map_data("state")
map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))

state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))

rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"
)

#categorize ranks
categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}

map_data$rank_category <- sapply(map_data$capital_disbursement_perlm_score_rank, categorize_rank)

# Plotting rank 
ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
 
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, capital_disbursement_perlm_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Capital Disbursements Per Lane-Mile Rank", fill = "Rank")

```

```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(maps) 


score_table <- scores_rankings %>%
  select(state, maintenance_disbursement_perlm_score_rank) %>%
  mutate(
    state_lower = tolower(state), 
    state_abb = state.abb[match(state, state.name)] 
  )


states_map <- map_data("state")
map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))


rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"
)


categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}


map_data$rank_category <- sapply(map_data$maintenance_disbursement_perlm_score_rank, categorize_rank)

# Plotting the map for Maintenance Disbursements Per Lane-Mile Rank
ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, maintenance_disbursement_perlm_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Maintenance Disbursements Per Lane-Mile Rank", fill = "Rank")

```


```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(maps) 



score_table <- scores_rankings %>%
  select(state, admin_disbursement_perlm_score_rank) %>%
  mutate(
    state_lower = tolower(state), 
    state_abb = state.abb[match(state, state.name)] 
  )


states_map <- map_data("state")
map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))


rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"
)


categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}


map_data$rank_category <- sapply(map_data$admin_disbursement_perlm_score_rank, categorize_rank)


ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, admin_disbursement_perlm_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Administrative Disbursements Per Lane-Mile Rank", fill = "Rank")


```

```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(maps)


score_table <- scores_rankings %>%
  select(state, other_disbursement_perlm_score_rank) %>%
  mutate(
    state_lower = tolower(state),
    state_abb = state.abb[match(state, state.name)] 
  )


states_map <- map_data("state")
map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))


alaska <- map_data[map_data$region == "alaska", ]
hawaii <- map_data[map_data$region == "hawaii", ]


alaska <- alaska %>%
  mutate(long = long * 0.35 + 130, lat = lat * 0.35 - 20)
hawaii <- hawaii %>%
  mutate(long = long * 1.2 + 50, lat = lat * 1.2 - 25)


map_data <- map_data %>%
  filter(!region %in% c("alaska", "hawaii")) %>%
  bind_rows(alaska, hawaii)


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))


rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"
)


categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}


map_data$rank_category <- sapply(map_data$other_disbursement_perlm_score_rank, categorize_rank)


ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, other_disbursement_perlm_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Other Disbursements Per Lane-Mile Rank", fill = "Rank") +
  coord_fixed(1.3)  

```


```{r}

library(readxl)
library(dplyr)
library(reactable)
library(htmltools)


create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  if (is.na(value)) return("")  # Return empty for NA values
  width_percent <- 100 * value / max_value  
  bar_style <- list(
    display = "inline-block",
    verticalAlign = "middle",  
    width = paste0(width_percent, "%"),  
    height = "15px",  # Bar height
    backgroundColor = color
  )
  
  
  div(style = "display: flex; align-items: center;",  
      div(style = bar_style),  
      div(style = "margin-left: 8px;", format(round(value, 2), big.mark = ",", scientific = FALSE))  
  )
}


table_data <- scores_rankings %>%
  select(state, rural_interstate_poor_percent_score) %>%
  filter(!is.na(rural_interstate_poor_percent_score) & rural_interstate_poor_percent_score > 0) %>%
  arrange(rural_interstate_poor_percent_score) %>%
  mutate(rank = row_number())  


table_data <- table_data %>%
  select(rank, state, rural_interstate_poor_percent_score)


max_rural_poor_percent <- max(table_data$rural_interstate_poor_percent_score, na.rm = TRUE)


reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),  
    state = colDef(name = "State"),  
    rural_interstate_poor_percent_score = colDef(
      name = "Percent Rural Interstate Mileage in Poor Condition",
      cell = function(value) {
        create_bar_chart(value, max_rural_poor_percent, "#FFCC33")  
      },
      minWidth = 180  
    )
  ),
  defaultSorted = "rank",
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)

```


```{r}

library(ggplot2)
library(dplyr)
library(usmap) 


score_table <- scores_rankings %>%
  select(state, other_disbursement_perlm_score_rank) %>%
  mutate(
    state_abb = state.abb[match(state, state.name)] 
  )


us_map_data <- plot_usmap(
  regions = "states", 
  data = score_table, 
  values = "other_disbursement_perlm_score_rank", 
  include = c("AK", "HI", state.abb)  # Include AK and HI explicitly
) + 
  scale_fill_continuous(
    low = "green", high = "red", 
    name = "Rank", label = scales::comma
  ) + 
  theme(legend.position = "right") +
  labs(title = "Other Disbursements Per Lane-Mile Rank")

# Plot the map
print(us_map_data)

```


```{r}


library(readxl)
library(dplyr)
library(ggplot2)
library(maps)  
library(ggthemes)


score_table <- scores_rankings %>%
  select(state, rural_interstate_poor_percent_score_rank) %>%
  mutate(
    state_lower = tolower(state),  
    state_abb = state.abb[match(state, state.name)]  
  )


states_map <- map_data("state")

map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))


rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"
)


categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}


map_data$rank_category <- sapply(map_data$rural_interstate_poor_percent_score_rank, categorize_rank)


ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, rural_interstate_poor_percent_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Percent of Rural Interstates in Poor Condition", fill = "Rank") +
  coord_fixed(1.3)

```

```{r}

library(readxl)
library(dplyr)
library(reactable)
library(htmltools)  


create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  width_percent <- 100 * value / max_value  
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"), 
    height = "15px",  
    backgroundColor = color,
    textAlign = "center",  
    verticalAlign = "middle",  
    whiteSpace = "nowrap"  
  )
  
  div(style = "display: flex; align-items: center;", 
      div(style = bar_style),  
      div(style = "padding-left: 10px;", sprintf("%.2f", value))  #
  )
}


table_data <- scores_rankings %>%
  select(state, urban_interstate_poor_percent_score) %>%
  filter(!is.na(urban_interstate_poor_percent_score) & urban_interstate_poor_percent_score > 0) %>%
  arrange(urban_interstate_poor_percent_score) %>%
  mutate(rank = row_number())  


table_data <- table_data %>%
  select(rank, state, urban_interstate_poor_percent_score)


max_value <- max(table_data$urban_interstate_poor_percent_score, na.rm = TRUE)


reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),  
    state = colDef(name = "State"),  
    urban_interstate_poor_percent_score = colDef(
      name = "Percent Urban Interstate Mileage in Poor Condition",
      cell = function(value) {
        create_bar_chart(value, max_value)  
      },
      minWidth = 250  
    )
  ),
  defaultSorted = "rank",
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)


```


```{r}

library(ggplot2)
library(dplyr)
library(maps)  
library(readxl)


score_table <- scores_rankings %>%
  select(state, urban_interstate_poor_percent_score_rank) %>%
  mutate(
    state_lower = tolower(state),  
    state_abb = state.abb[match(state, state.name)]  
  )


states_map <- map_data("state")


map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))


rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"
)


categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}


map_data$rank_category <- sapply(map_data$urban_interstate_poor_percent_score_rank, categorize_rank)


ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  coord_map() +  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, urban_interstate_poor_percent_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Percent of Urban Interstates in Poor Condition", fill = "Rank")


```


```{r}


library(readxl)
library(dplyr)
library(reactable)
library(htmltools)  


create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  width_percent <- 100 * value / max_value  
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"), 
    height = "15px",  
    backgroundColor = color,
    textAlign = "center",  
    verticalAlign = "middle",  
    whiteSpace = "nowrap"  
  )
  
  div(style = "display: flex; align-items: center;", 
      div(style = bar_style),  # Bar itself
      div(style = "padding-left: 10px;", format(round(value, 2), big.mark = ",", scientific = FALSE))  
  )
}

table_data <- scores_rankings %>%
  select(state, rural_OPA_poor_percent_score) %>%
  filter(!is.na(rural_OPA_poor_percent_score) & rural_OPA_poor_percent_score > 0) %>%
  arrange(rural_OPA_poor_percent_score) %>%
  mutate(rank = row_number())  


table_data <- table_data %>%
  select(rank, state, rural_OPA_poor_percent_score)


max_value <- max(table_data$rural_OPA_poor_percent_score, na.rm = TRUE)


reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),  
    state = colDef(name = "State"),  
    rural_OPA_poor_percent_score = colDef(
      name = "Percent Rural Other Principal Arterial Mileage in Poor Condition",
      cell = function(value) {
        create_bar_chart(value, max_value)  
      },
      minWidth = 250  
    )
  ),
  defaultSorted = "rank",
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)


```

```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(maps)  

states_map <- map_data("state")


score_table <- scores_rankings %>%
  select(state, rural_OPA_poor_percent_score_rank) %>%
  mutate(
    state_lower = tolower(state),  
    state_abb = state.abb[match(state, state.name)]  
  )


map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))


rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"
)


categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}


map_data$rank_category <- sapply(map_data$rural_OPA_poor_percent_score_rank, categorize_rank)


ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, rural_OPA_poor_percent_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Rural OPA Percent Mileage in Poor Condition Rank", fill = "Rank")

```

```{r}

library(readxl)
library(dplyr)
library(reactable)
library(htmltools)  

create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  width_percent <- 100 * value / max_value  
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"),  
    height = "15px",  
    backgroundColor = color,
    textAlign = "center",  
    verticalAlign = "middle",  
    whiteSpace = "nowrap"  
  )
  
  div(style = "display: flex; align-items: center;", 
      div(style = bar_style),  
      div(style = "padding-left: 10px;", format(round(value, 2), big.mark = ",", scientific = FALSE))  
  )
}

table_data <- scores_rankings %>%
  select(state, urban_OPA_poor_percent_score) %>%
  filter(!is.na(urban_OPA_poor_percent_score) & urban_OPA_poor_percent_score > 0) %>%
  arrange(urban_OPA_poor_percent_score) %>%
  mutate(rank = row_number())  


table_data <- table_data %>%
  select(rank, state, urban_OPA_poor_percent_score)


max_value <- max(table_data$urban_OPA_poor_percent_score, na.rm = TRUE)


reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),  
    state = colDef(name = "State"),  
    urban_OPA_poor_percent_score = colDef(
      name = "Percent Urban OPA Mileage in Poor Condition",
      cell = function(value) {
        create_bar_chart(value, max_value)  
      },
      minWidth = 250  
    )
  ),
  defaultSorted = "rank",
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)


```

```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(maps)  

score_table <- scores_rankings %>%
  select(state, urban_OPA_poor_percent_score_rank) %>%
  mutate(
    state_lower = tolower(state),  
    state_abb = state.abb[match(state, state.name)]  
  )


states_map <- map_data("state")

map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))
# Define rank colors
rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"  # Color for states without data
)

categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}


map_data$rank_category <- sapply(map_data$urban_OPA_poor_percent_score_rank, categorize_rank)

ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, urban_OPA_poor_percent_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Percent Urban OPA Mileage in Poor Condition Rank", fill = "Rank") +
  theme(
    plot.title = element_text(hjust = 0.5),  
    legend.position = "right"  
  )


```

```{r}

library(readxl)
library(dplyr)
library(reactable)
library(htmltools)


create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  width_percent <- 100 * value / max_value  
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"),  
    height = "15px",  
    backgroundColor = color,
    textAlign = "center",  
    verticalAlign = "middle",  
    whiteSpace = "nowrap"  
  )
  
  div(style = "display: flex; align-items: center;", 
      div(style = bar_style),  
      div(style = "padding-left: 10px;", format(round(value, 2), big.mark = ",", scientific = FALSE))  
  )
}


table_data <- scores_rankings %>%
  select(state, state_avg_congestion_hours_score) %>%
  filter(!is.na(state_avg_congestion_hours_score) & state_avg_congestion_hours_score > 0) %>%
  arrange(state_avg_congestion_hours_score)  


table_data <- table_data %>%
  mutate(rank = row_number())  


table_data <- table_data %>%
  select(rank, state, state_avg_congestion_hours_score)


max_value <- max(table_data$state_avg_congestion_hours_score, na.rm = TRUE)


reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),  
    state = colDef(name = "State"),  
    state_avg_congestion_hours_score = colDef(
      name = "Average Congestion Hours (State)", 
      cell = function(value) {
        create_bar_chart(value, max_value)  
      },
      format = colFormat(digits = 2),  
      minWidth = 250  
    )
  ),
  defaultSorted = "state_avg_congestion_hours_score",  
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)

```

```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(maps) 


score_table <- scores_rankings %>%
  select(state, state_avg_congestion_hours_score_rank) %>%
  mutate(
    state_lower = tolower(state),  
    state_abb = state.abb[match(state, state.name)]  
  )


states_map <- map_data("state")


map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))


state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))


rank_colors <- c(
  "1 to 10" = "#66bb6a",  # Green
  "11 to 20" = "#b2df8a",  # Light Green
  "21 to 30" = "#ffeb3b",  # Yellow
  "31 to 40" = "#ff7043",  # Orange
  "41 to 50" = "#d32f2f",  # Red
  "Not ranked" = "gray"  # Color for states without data
)


categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}


map_data$rank_category <- sapply(map_data$state_avg_congestion_hours_score_rank, categorize_rank)


ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, state_avg_congestion_hours_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "State Average Congestion Hours Score Rank", fill = "Rank") +
  theme(
    plot.title = element_text(hjust = 0.5),  
    legend.position = "right"  
  ) +
  coord_map()


```

```{r}

library(readxl)
library(dplyr)
library(reactable)
library(htmltools)  


create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  width_percent <- 100 * value / max_value  
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"),  
    height = "15px",  
    backgroundColor = color,
    textAlign = "center", 
    verticalAlign = "middle",  
    whiteSpace = "nowrap"  
  )
  
  div(style = "display: flex; align-items: center;", 
      div(style = bar_style), 
      div(style = "padding-left: 10px;", sprintf("%.2f", value))  
  )
}

# Filtering the data
table_data <- scores_rankings %>%
  select(state, poor_bridges_percent_score) %>%
  filter(!is.na(poor_bridges_percent_score) & poor_bridges_percent_score > 0) %>%
  arrange(poor_bridges_percent_score) %>%
  mutate(rank = row_number())  


table_data <- table_data %>%
  select(rank, state, poor_bridges_percent_score)


max_value <- max(table_data$poor_bridges_percent_score, na.rm = TRUE)


reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),  
    state = colDef(name = "State"),  
    poor_bridges_percent_score = colDef(
      name = "Poor Bridges Percent Score",
      cell = function(value) {
        create_bar_chart(value, max_value)  
      },
      minWidth = 250  
    )
  ),
  defaultSorted = "rank",
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)


```


```{r}


library(readxl)
library(dplyr)
library(ggplot2)
library(maps)

score_table <- scores_rankings %>%
  select(state, poor_bridges_percent_score_rank) %>%
  mutate(
    state_lower = tolower(state),
    state_abb = state.abb[match(state, state.name)]
  )

states_map <- map_data("state")
map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))

state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))

rank_colors <- c(
  "1 to 10" = "#66bb6a",
  "11 to 20" = "#b2df8a",
  "21 to 30" = "#ffeb3b",
  "31 to 40" = "#ff7043",
  "41 to 50" = "#d32f2f",
  "Not ranked" = "gray"
)

categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}

map_data$rank_category <- sapply(map_data$poor_bridges_percent_score_rank, categorize_rank)

ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, poor_bridges_percent_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Percent Structurally Deficient Bridges Rank", fill = "Rank") +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "right"
  )


```


```{r}
library(readxl)
library(dplyr)
library(reactable)
library(htmltools) 

create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  width_percent <- 100 * value / max_value  
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"),  
    height = "15px",  
    backgroundColor = color,
    textAlign = "center",  
    verticalAlign = "middle",  
    whiteSpace = "nowrap"  
  )
  div(style = "display: flex; align-items: center;", 
      div(style = bar_style),  
      div(style = "padding-left: 10px;", format(round(value, 2), big.mark = ",", scientific = FALSE))  
  )
}

table_data <- scores_rankings %>%
  select(state, rural_fatalities_per_100m_VMT_score) %>%
  filter(!is.na(rural_fatalities_per_100m_VMT_score) & rural_fatalities_per_100m_VMT_score > 0) %>%
  arrange(rural_fatalities_per_100m_VMT_score) %>%
  mutate(rank = row_number()) 

table_data <- table_data %>%
  select(rank, state, rural_fatalities_per_100m_VMT_score)

max_value <- max(table_data$rural_fatalities_per_100m_VMT_score, na.rm = TRUE)

reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),
    state = colDef(name = "State"),
    rural_fatalities_per_100m_VMT_score = colDef(
      name = "Fatality Rate Per 100M Rural VMT",
      cell = function(value) {
        create_bar_chart(value, max_value)
      },
      minWidth = 250  
    )
  ),
  defaultSorted = "rank",
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)


```


```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(maps)

score_table <- scores_rankings %>%
  select(state, rural_fatalities_per_100m_VMT_score_rank) %>%
  mutate(
    state_lower = tolower(state),  
    state_abb = state.abb[match(state, state.name)]  
  )

states_map <- map_data("state")

map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))

state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))

rank_colors <- c(
  "1 to 10" = "#66bb6a",  
  "11 to 20" = "#b2df8a",  
  "21 to 30" = "#ffeb3b",  
  "31 to 40" = "#ff7043",  
  "41 to 50" = "#d32f2f",  
  "Not ranked" = "gray"  
)

categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}

map_data$rank_category <- sapply(map_data$rural_fatalities_per_100m_VMT_score_rank, categorize_rank)

ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, rural_fatalities_per_100m_VMT_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Fatality Rate Per 100M Rural VMT Rank", fill = "Rank") +
  theme(
    plot.title = element_text(hjust = 0.5),  
    legend.position = "right"  
  )



```


```{r}
library(readxl)
library(dplyr)
library(reactable)
library(htmltools)

create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  width_percent <- 100 * value / max_value
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"),
    height = "15px",
    backgroundColor = color,
    textAlign = "center",
    verticalAlign = "middle",
    whiteSpace = "nowrap"
  )
  div(style = "display: flex; align-items: center;", 
      div(style = bar_style),  
      div(style = "padding-left: 10px;", sprintf("%.2f", value))  # Ensures 2 digits after decimal
  )
}

table_data <- scores_rankings %>%
  select(state, urban_fatalities_per_100m_VMT_score) %>%
  filter(!is.na(urban_fatalities_per_100m_VMT_score) & urban_fatalities_per_100m_VMT_score > 0) %>%
  arrange(urban_fatalities_per_100m_VMT_score) %>%
  mutate(rank = row_number())

table_data <- table_data %>%
  select(rank, state, urban_fatalities_per_100m_VMT_score)

max_value <- max(table_data$urban_fatalities_per_100m_VMT_score, na.rm = TRUE)

reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),
    state = colDef(name = "State"),
    urban_fatalities_per_100m_VMT_score = colDef(
      name = "Fatality Rate Per 100M Urban Vehicle-Miles",
      cell = function(value) {
        create_bar_chart(value, max_value)
      },
      format = colFormat(digits = 2),
      minWidth = 250
    )
  ),
  defaultSorted = "rank",
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)


```

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(maps)

score_table <- scores_rankings %>%
  select(state, urban_fatalities_per_100m_VMT_score_rank) %>%
  mutate(
    state_lower = tolower(state), 
    state_abb = state.abb[match(state, state.name)]
  )

states_map <- map_data("state")
map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))

state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))

rank_colors <- c(
  "1 to 10" = "#66bb6a",  
  "11 to 20" = "#b2df8a",  
  "21 to 30" = "#ffeb3b",  
  "31 to 40" = "#ff7043",  
  "41 to 50" = "#d32f2f",  
  "Not ranked" = "gray"
)

categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}

map_data$rank_category <- sapply(map_data$urban_fatalities_per_100m_VMT_score_rank, categorize_rank)

ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, urban_fatalities_per_100m_VMT_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Urban Fatalities Per 100M Vehicle-Miles Rank", fill = "Rank") +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "right"
  )


```


```{r}
library(readxl)
library(dplyr)
library(reactable)
library(htmltools)

create_bar_chart <- function(value, max_value, color = "#FFCC33") {
  width_percent <- 100 * value / max_value
  bar_style <- list(
    display = "inline-block",
    width = paste0(width_percent, "%"),
    height = "15px",
    backgroundColor = color,
    textAlign = "center",
    verticalAlign = "middle",
    whiteSpace = "nowrap"
  )
  
  div(style = "display: flex; align-items: center;", 
      div(style = bar_style),
      div(style = "padding-left: 10px;", format(round(value, 2), big.mark = ",", scientific = FALSE))
  )
}

table_data <- scores_rankings %>%
  select(state, other_fatalities_per_100m_VMT_score) %>%
  filter(!is.na(other_fatalities_per_100m_VMT_score) & other_fatalities_per_100m_VMT_score > 0) %>%
  arrange(other_fatalities_per_100m_VMT_score) %>%
  mutate(rank = row_number())

table_data <- table_data %>%
  select(rank, state, other_fatalities_per_100m_VMT_score)

max_value <- max(table_data$other_fatalities_per_100m_VMT_score, na.rm = TRUE)

reactable(
  data = table_data,
  columns = list(
    rank = colDef(name = "Rank", align = "center"),
    state = colDef(name = "State"),
    other_fatalities_per_100m_VMT_score = colDef(
      name = "Other Fatalities Per 100M VMT",
      cell = function(value) {
        create_bar_chart(value, max_value)
      },
      minWidth = 250
    )
  ),
  defaultSorted = "rank",
  bordered = TRUE,
  highlight = TRUE,
  defaultPageSize = 10,
  striped = TRUE
)


```


```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(maps)

score_table <- scores_rankings %>%
  select(state, other_fatalities_per_100m_VMT_score_rank) %>%
  mutate(
    state_lower = tolower(state),  
    state_abb = state.abb[match(state, state.name)] 
  )

states_map <- map_data("state")

map_data <- left_join(states_map, score_table, by = c("region" = "state_lower"))

state_centers_df <- map_data %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat)) %>%
  left_join(score_table, by = c("region" = "state_lower"))

rank_colors <- c(
  "1 to 10" = "#66bb6a",  
  "11 to 20" = "#b2df8a",  
  "21 to 30" = "#ffeb3b",  
  "31 to 40" = "#ff7043",  
  "41 to 50" = "#d32f2f",  
  "Not ranked" = "gray"  
)

categorize_rank <- function(rank) {
  if (is.na(rank)) {
    return("Not ranked")
  } else if (rank <= 10) {
    return("1 to 10")
  } else if (rank <= 20) {
    return("11 to 20")
  } else if (rank <= 30) {
    return("21 to 30")
  } else if (rank <= 40) {
    return("31 to 40")
  } else {
    return("41 to 50")
  }
}

map_data$rank_category <- sapply(map_data$other_fatalities_per_100m_VMT_score_rank, categorize_rank)

ggplot() +
  geom_polygon(data = map_data, aes(x = long, y = lat, group = group, fill = rank_category), color = "white") +
  scale_fill_manual(values = rank_colors, breaks = names(rank_colors), na.value = "gray") +
  theme_minimal() +
  
  geom_text(data = state_centers_df, aes(x = long, y = lat, label = paste(state_abb, other_fatalities_per_100m_VMT_score_rank, sep = "\n")), size = 3, color = "black") +
  labs(title = "Other Fatalities Per 100M VMT Rank", fill = "Rank") +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "right"
  )

```


